import { ReactNode } from 'react'
import { Sidebar } from './components/sidebar'

interface AuthLayoutProps {
  children: ReactNode
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: AuthLayoutProps) {
  return (
    <div>
      <div>
        <Sidebar />
      </div>
      <div className="ml-64">{children}</div>
    </div>
  )
}
