import { ReactNode } from 'react'
import { Sidebar } from './components/sidebar'
import { ToastContainer } from 'react-toastify'

interface AuthLayoutProps {
  children: ReactNode
}

export const metadata = {
  title: 'Lexorama',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: AuthLayoutProps) {
  return (
    <div>
      <ToastContainer />
      <Sidebar />
      <div className="ml-72 p-6">{children}</div>
    </div>
  )
}
