import { ReactNode } from 'react'
import { Sidebar } from './components/sidebar'

interface AuthLayoutProps {
  children: ReactNode
}

export const metadata = {
  title: 'Lexorama',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: AuthLayoutProps) {
  return (
    <div>
      <div>
        <Sidebar />
      </div>
      <div className="ml-72 p-6">{children}</div>
    </div>
  )
}
